### ISSUE TITLE
Kotlin detection throws an exception in java project

### ISSUE THREAD

**Issue by jorki02** [ydb-platform/yoj-project#23]
Seems like KotlinReflectionDetector.detectKotlinReflection not suitable for checking presence of Kotlin in the project, since java project can have dependencies on Kotlin library in this case it throws exception

2024-02-08T17:08:52.847+01:00  WARN 7670 --- [    Test worker] t.y.y.d.s.r.KotlinReflectionDetector     : YOJ has detected Kotlin but not kotlin-reflect. Kotlin data classes won't work as Entities.

java.lang.ClassNotFoundException: kotlin.reflect.full.KClasses
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:534) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:513) ~[?:?]
	at tech.ydb.yoj.databind.schema.reflect.KotlinReflectionDetector.detectKotlinReflection(KotlinReflectionDetector.java:24) ~[yoj-databind-1.1.2.jar:?]
	at tech.ydb.yoj.databind.schema.reflect.KotlinReflectionDetector.<clinit>(KotlinReflectionDetector.java:12) ~[yoj-databind-1.1.2.jar:?]
	at tech.ydb.yoj.databind.schema.reflect.KotlinDataClassTypeFactory.matches(KotlinDataClassTypeFactory.java:31) ~[yoj-databind-1.1.2.jar:?]
	at tech.ydb.yoj.databind.schema.reflect.StdReflector.reflectFor(StdReflector.java:58) ~[yoj-databind-1.1.2.jar:?]
	at tech.ydb.yoj.databind.schema.reflect.StdReflector.reflectRootType(StdReflector.java:43) ~[yoj-databind-1.1.2.jar:?]
	at tech.ydb.yoj.databind.schema.Schema.<init>(Schema.java:91) ~[yoj-databind-1.1.2.jar:?]
	at tech.ydb.yoj.repository.db.EntitySchema.<init>(EntitySchema.java:49) ~[yoj-repository-1.1.2.jar:?]
	at tech.ydb.yoj.repository.db.EntitySchema.lambda$of$0(EntitySchema.java:45) ~[yoj-repository-1.1.2.jar:?]
	at tech.ydb.yoj.databind.schema.configuration.SchemaRegistry$Schemas.lambda$getOrCreate$0(SchemaRegistry.java:92) ~[yoj-databind-1.1.2.jar:?]
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
	at tech.ydb.yoj.databind.schema.configuration.SchemaRegistry$Schemas.getOrCreate(SchemaRegistry.java:92) ~[yoj-databind-1.1.2.jar:?]
	at tech.ydb.yoj.databind.schema.configuration.SchemaRegistry.getOrCreate(SchemaRegistry.java:41) ~[yoj-databind-1.1.2.jar:?]
	at tech.ydb.yoj.repository.db.EntitySchema.of(EntitySchema.java:45) ~[yoj-repository-1.1.2.jar:?]
	at tech.ydb.yoj.repository.db.EntitySchema.of(EntitySchema.java:41) ~[yoj-repository-1.1.2.jar:?]
	at tech.ydb.yoj.repository.db.EntitySchema.of(EntitySchema.java:30) ~[yoj-repository-1.1.2.jar:?]
	at tech.ydb.yoj.repository.db.EntitySchema.of(EntitySchema.java:26) ~[yoj-repository-1.1.2.jar:?]
	at tech.ydb.yoj.repository.test.inmemory.InMemoryDataShard.<init>(InMemoryDataShard.java:36) ~[yoj-repository-inmemory-1.1.2.jar:?]
	at tech.ydb.yoj.repository.test.inmemory.InMemoryStorage.createTable(InMemoryStorage.java:105) ~[yoj-repository-inmemory-1.1.2.jar:?]
	at tech.ydb.yoj.repository.test.inmemory.InMemoryRepository$1.create(InMemoryRepository.java:55) ~[yoj-repository-inmemory-1.1.2.jar:?]

**Comment by nvamelichev** [comment]
Oh. This is just a warning that appears if you depend on Kotlin but not `kotlin-reflect`, including transitively.

It can safely be ignored. I may lower the message level to INFO, but then someone using Kotlin without reflection will likely miss it :-(
